name: magic_ledger
description: "A neo-brutalist expense and todo tracker app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Animations
  flutter_animate: ^4.5.2

  # Charts & Analytics
  fl_chart: ^1.0.0

  # PDF Generation
  pdf: ^3.11.3
  printing: ^5.14.2

  # Image Handling
  image_picker: ^1.1.2
  path_provider: ^2.1.5

  # Notifications
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false  # Set to true if you want iOS icons too
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#181C27"  # Your dark theme color
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/SpaceGrotesk-Regular.ttf
        - asset: fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: fonts/SpaceGrotesk-Bold.ttf
          weight: 700